name: MLOps Pipeline

on:
  push:
    branches: [main]

jobs:
  mlops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r deployment/requirements.txt
          pip install dvc[all] mlflow

      - name: Data Ingestion
        run: python data_ingestion/ingest.py

      - name: Data Validation
        run: python data_validation/validate.py

      - name: Feature Engineering
        run: python feature_engineering/features.py

      - name: Model Training
        run: python model/train.py

      - name: Model Evaluation
        run: python model/evaluate.py

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model/model.pkl

      - name: Docker Build & Push (optional)
        run: |
          docker build -t yourdockerhub/yourmodel:latest .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push yourdockerhub/yourmodel:latest
